import type { Metadata } from "next";
import { Geist, Geist_Mono, Onest, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-primary",
});
 const fontHeading = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-heading"
 })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} ${fontHeading.variable} antialiased`}>{children}</body>
    </html>
  );
}
