'use client'

import { ChangeEvent, FormEvent, useRef, useState } from 'react'
import Image from 'next/image'
import { FiPlus, FiX } from 'react-icons/fi'

type Props = {
    type: 'blog' | 'partner'
    isSubmitting: boolean
    onClose: () => void
    onBlogSubmit: (event: FormEvent<HTMLFormElement>) => void
    onPartnerSubmit: (event: FormEvent<HTMLFormElement>) => void
}

export default function AdminComposer({ type, isSubmitting, onClose, onBlogSubmit, onPartnerSubmit }: Props) {
    const isBlog = type === 'blog'
    return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#063f70]/30 p-0 backdrop-blur-sm sm:items-center sm:p-6">
        <div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-2xl sm:p-8">
            <div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#066ac0]">New {isBlog ? 'content' : 'connection'}</p><h2 className="mt-2 font-heading text-2xl font-bold">Add {isBlog ? 'a blog post' : 'a partner'}</h2><p className="mt-1 text-sm text-[#819096]">{isBlog ? 'Write and format your story before saving it to MongoDB.' : 'Add a business to your SwiftRun partner network.'}</p></div><button onClick={onClose} className="rounded-lg p-2 text-[#718187]" aria-label="Close form"><FiX /></button></div>
            {isBlog ? <BlogForm isSubmitting={isSubmitting} onSubmit={onBlogSubmit} onClose={onClose} /> : <PartnerForm isSubmitting={isSubmitting} onSubmit={onPartnerSubmit} onClose={onClose} />}
        </div>
    </div>
}

function LegacyBlogForm({ onSubmit, onClose }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void; onClose: () => void }) {
    const editorRef = useRef<HTMLDivElement>(null)
    const [content, setContent] = useState('')
    const runCommand = (command: string, value?: string) => { editorRef.current?.focus(); document.execCommand(command, false, value); setContent(editorRef.current?.innerHTML || '') }
    return <form onSubmit={onSubmit} className="mt-7 space-y-5">
        <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Post title</span><input required name="title" placeholder="e.g. The future of local delivery" className="w-full rounded-xl border border-[#d9e5e1] px-4 py-3 text-sm outline-none focus:border-[#066ac0]" /></label>
        <div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Description</span><textarea required name="description" rows={3} placeholder="A short summary for cards and search results" className="w-full resize-none rounded-xl border border-[#d9e5e1] px-4 py-3 text-sm outline-none focus:border-[#066ac0]" /></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Category</span><select name="category" className="w-full rounded-xl border border-[#d9e5e1] bg-white px-4 py-3 text-sm outline-none focus:border-[#066ac0]"><option>Product</option><option>Business</option><option>Community</option><option>How Tos</option><option>News</option></select></label></div>
        <div><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Article content</span><div className="overflow-hidden rounded-xl border border-[#d9e5e1] focus-within:border-[#066ac0]"><div className="flex flex-wrap gap-1 border-b border-[#edf1ef] bg-[#f8faf9] p-2"><button type="button" onClick={() => runCommand('bold')} className="rounded-lg px-3 py-1.5 text-sm font-bold hover:bg-white">B</button><button type="button" onClick={() => runCommand('italic')} className="rounded-lg px-3 py-1.5 text-sm italic hover:bg-white">I</button><button type="button" onClick={() => runCommand('formatBlock', 'h2')} className="rounded-lg px-3 py-1.5 text-xs font-bold hover:bg-white">H2</button><button type="button" onClick={() => runCommand('insertUnorderedList')} className="rounded-lg px-3 py-1.5 text-sm hover:bg-white">List</button><button type="button" onClick={() => { const url = window.prompt('Enter a link URL'); if (url) runCommand('createLink', url) }} className="rounded-lg px-3 py-1.5 text-sm hover:bg-white">Link</button></div><div ref={editorRef} contentEditable role="textbox" aria-label="Article content" onInput={() => setContent(editorRef.current?.innerHTML || '')} data-placeholder="Start writing your article..." className="min-h-44 p-4 text-sm leading-7 outline-none empty:before:text-[#a5b0b2] empty:before:content-[attr(data-placeholder)]" /><input type="hidden" name="content" value={content} /></div></div>
        <div className="flex justify-end gap-3 border-t border-[#edf1ef] pt-5"><button type="button" onClick={onClose} className="rounded-xl px-4 py-3 text-sm font-bold text-[#718187]">Cancel</button><button type="submit" className="flex items-center gap-2 rounded-xl bg-[#066ac0] px-5 py-3 text-sm font-bold text-white"><FiPlus /> Save draft</button></div>
    </form>
}

function PartnerForm({ isSubmitting, onSubmit, onClose }: { isSubmitting: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onClose: () => void }) { return <form onSubmit={onSubmit} className="mt-7 space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Business name</span><input required name="name" placeholder="e.g. The Green Basket" className="w-full rounded-xl border border-[#d9e5e1] px-4 py-3 text-sm outline-none focus:border-[#066ac0]" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Business type</span><select name="category" className="w-full rounded-xl border border-[#d9e5e1] bg-white px-4 py-3 text-sm outline-none focus:border-[#066ac0]"><option>Groceries</option><option>Restaurant</option><option>Healthcare</option><option>Other</option></select></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Location</span><input name="location" defaultValue="Lagos, NG" className="w-full rounded-xl border border-[#d9e5e1] px-4 py-3 text-sm outline-none focus:border-[#066ac0]" /></label></div><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Partner URL</span><input required type="url" name="url" placeholder="https://example.com" className="w-full rounded-xl border border-[#d9e5e1] px-4 py-3 text-sm outline-none focus:border-[#066ac0]" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Partner image</span><input required type="file" name="imageFile" accept="image/png,image/jpeg,image/webp" className="w-full rounded-xl border border-dashed border-[#b7cfc8] px-3 py-2.5 text-xs text-[#819096]" /></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Partner logo</span><input required type="file" name="logoFile" accept="image/png,image/jpeg,image/webp" className="w-full rounded-xl border border-dashed border-[#b7cfc8] px-3 py-2.5 text-xs text-[#819096]" /></label></div><div className="flex justify-end gap-3 border-t border-[#edf1ef] pt-5"><button type="button" disabled={isSubmitting} onClick={onClose} className="rounded-xl px-4 py-3 text-sm font-bold text-[#718187] disabled:opacity-40">Cancel</button><button type="submit" disabled={isSubmitting} className="flex min-w-32 items-center justify-center gap-2 rounded-xl bg-[#066ac0] px-5 py-3 text-sm font-bold text-white disabled:cursor-wait disabled:opacity-80">{isSubmitting ? <><span className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white" /> Uploading...</> : <><FiPlus /> Add partner</>}</button></div></form> }

function BlogForm({ isSubmitting, onSubmit, onClose }: { isSubmitting: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onClose: () => void }) {
    const editorRef = useRef<HTMLDivElement>(null)
    const [content, setContent] = useState('')
    const [image, setImage] = useState('')
    const runCommand = (command: string, value?: string) => { editorRef.current?.focus(); document.execCommand(command, false, value); setContent(editorRef.current?.innerHTML || '') }
    const handleImage = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setImage(String(reader.result)); reader.readAsDataURL(file) }
    return <form onSubmit={onSubmit} className="mt-7 space-y-5">
        <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Post title</span><input required name="title" placeholder="e.g. The future of local delivery" className="w-full rounded-xl border border-[#d9e5e1] px-4 py-3 text-sm outline-none focus:border-[#066ac0]" /></label>
        <div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Category</span><select name="category" className="w-full rounded-xl border border-[#d9e5e1] bg-white px-4 py-3 text-sm outline-none focus:border-[#066ac0]"><option>Product</option><option>Business</option><option>Community</option><option>How Tos</option><option>News</option></select></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Cover image</span><input required type="file" name="imageFile" accept="image/png,image/jpeg,image/webp" onChange={handleImage} className="w-full rounded-xl border border-dashed border-[#b7cfc8] px-3 py-2.5 text-xs text-[#819096]" /></label></div>
        {image && <Image src={image} alt="Selected blog cover preview" width={900} height={240} unoptimized className="h-36 w-full rounded-xl object-cover" />}
        <div><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-[#718187]">Article content</span><div className="overflow-hidden rounded-xl border border-[#d9e5e1] focus-within:border-[#066ac0]"><div className="flex flex-wrap gap-1 border-b border-[#edf1ef] bg-[#f8faf9] p-2"><button type="button" onClick={() => runCommand('bold')} className="rounded-lg px-3 py-1.5 text-sm font-bold hover:bg-white">B</button><button type="button" onClick={() => runCommand('italic')} className="rounded-lg px-3 py-1.5 text-sm italic hover:bg-white">I</button><button type="button" onClick={() => runCommand('formatBlock', 'h2')} className="rounded-lg px-3 py-1.5 text-xs font-bold hover:bg-white">H2</button><button type="button" onClick={() => runCommand('insertUnorderedList')} className="rounded-lg px-3 py-1.5 text-sm hover:bg-white">List</button><button type="button" onClick={() => { const url = window.prompt('Enter a link URL'); if (url) runCommand('createLink', url) }} className="rounded-lg px-3 py-1.5 text-sm hover:bg-white">Link</button></div><div ref={editorRef} contentEditable role="textbox" aria-label="Article content" onInput={() => setContent(editorRef.current?.innerHTML || '')} data-placeholder="Start writing your article..." className="min-h-44 p-4 text-sm leading-7 outline-none empty:before:text-[#a5b0b2] empty:before:content-[attr(data-placeholder)]" /><input type="hidden" name="content" value={content} /></div></div>
        <div className="flex justify-end gap-3 border-t border-[#edf1ef] pt-5"><button type="button" disabled={isSubmitting} onClick={onClose} className="rounded-xl px-4 py-3 text-sm font-bold text-[#718187] disabled:opacity-40">Cancel</button><button type="submit" disabled={isSubmitting} className="flex min-w-32 items-center justify-center gap-2 rounded-xl bg-[#066ac0] px-5 py-3 text-sm font-bold text-white disabled:cursor-wait disabled:opacity-80">{isSubmitting ? <><span className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white" /> Uploading...</> : <><FiPlus /> Save draft</>}</button></div>
    </form>
}

void LegacyBlogForm
